# Generated by Django 3.1.7 on 2021-03-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
        migrations.RemoveField(
            model_name='author',
            name='display_email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='author',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='author',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
        migrations.RemoveField(
            model_name='author',
            name='youtube_link',
        ),
    ]
