# Generated by Django 3.1.7 on 2021-03-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
    ]
