# Generated by Django 3.1.7 on 2021-03-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210305_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
