# Generated by Django 3.1.7 on 2021-03-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
