# Generated by Django 3.1.7 on 2021-03-26 21:17

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to=posts.models.featured_image_path),
        ),
    ]
