# Generated by Django 3.1.7 on 2021-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210602_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=250, unique=True),
        ),
    ]
