# Generated by Django 3.1.7 on 2021-02-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=2, max_length=100, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
