# Generated by Django 3.1.7 on 2021-03-01 13:28

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210301_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser')),
                ('profile_picture', models.ImageField(default='static/images/default_profile.png', upload_to=accounts.models.profile_pic_filename)),
                ('website', models.URLField(blank=True)),
                ('country', django_countries.fields.CountryField(default='TZ', max_length=2, verbose_name='Country')),
                ('location', models.CharField(max_length=200)),
                ('display_email', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('youtube_link', models.URLField(verbose_name='Youtube URL')),
                ('facebook_link', models.URLField(verbose_name='Facebook URL')),
                ('instagram_link', models.URLField(verbose_name='Instagram URL')),
                ('linkedin_link', models.URLField(verbose_name='Linkedin URL')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
