# Generated by Django 3.1.7 on 2021-03-18 10:23

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210317_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=s3direct.fields.S3DirectField(default='profile_pics/default_profile.png'),
        ),
    ]
