# Generated by Django 3.1.7 on 2021-03-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210329_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
