# Generated by Django 3.1.7 on 2021-03-18 14:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210318_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to=accounts.models.profile_pic_filename),
        ),
    ]
